from __future__ import annotations

import pytest

from commitminer.languages import Language, language_of
from commitminer.signals import (
    GENERATED_HEADER,
    HEADER_LINES,
    MAX_CONTENT,
    MINIFIED,
    RUST_INLINE_TESTS,
    SIGNALS,
    count_test_functions,
    detect,
    detect_path,
    has_generated_header,
    has_inline_tests,
    is_minified,
    rust_tests_added,
)


@pytest.mark.parametrize(
    ("path", "language"),
    [
        ("src/a.py", Language.PYTHON),
        ("stubs/a.PYI", Language.PYTHON),
        ("src/lib.rs", Language.RUST),
        ("web/app.JSX", Language.JAVASCRIPT),
        ("web/app.cjs", Language.JAVASCRIPT),
        ("web/app.mts", Language.TYPESCRIPT),
        ("types/index.d.ts", Language.TYPESCRIPT),
        ("main.go", Language.GO),
        ("src\\main\\java\\A.java", Language.JAVA),
        ("README.md", None),
        ("Makefile", None),
        (".js", None),
        ("dir.py/file", None),
    ],
)
def test_language_of(path: str, language: Language | None) -> None:
    assert language_of(path) == language


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("// Code generated by protoc-gen-go. DO NOT EDIT.\n", True),
        ("# Generated by the protocol buffer compiler.  DO NOT EDIT!\n", True),
        ("/* @generated */\n", True),
        (" * This file is automatically generated.\n", True),
        ('"""Auto-generated from schema.json; do not modify."""\n', True),
        ("// DO NOT EDIT: generated by make tables\n", True),
        ("// machine generated, see gen.py\n", True),
        ("# Generate the lookup table on first use.\n", False),
        ("# generated values are cached\n", False),
        ('MARK = "@generated"\n', False),
        ("x = 1  # @generated\n", False),
        ("", False),
    ],
)
def test_generated_header(text: str, expected: bool) -> None:
    assert has_generated_header(text) is expected


def test_generated_header_must_be_in_the_first_lines() -> None:
    marker = "// Code generated by x. DO NOT EDIT.\n"
    assert has_generated_header("\n" * (HEADER_LINES - 1) + marker)
    assert not has_generated_header("\n" * HEADER_LINES + marker)


def test_minified_thresholds() -> None:
    assert is_minified("a" * 512)
    assert not is_minified("a" * 511)
    # 1000 characters (newlines included) over five lines average exactly 200.
    assert is_minified("\n".join(["b" * 199] * 4 + ["b" * 200]))
    assert not is_minified("\n".join(["b" * 150] * 10))
    # One long data line among many short ones stays hand-written.
    assert not is_minified("x\n" * 100 + "y" * 5000)


def test_inline_tests_and_test_counting() -> None:
    source = "#[cfg(test)]\nmod tests {\n    #[test]\n    fn a() {}\n    #[tokio::test]\n"
    source += "    async fn b() {}\n    #[test_case(1)]\n    fn c() {}\n}\n"
    assert has_inline_tests(source)
    assert count_test_functions(source) == 2
    assert count_test_functions('#[tokio::test(flavor = "multi_thread")]\n') == 1
    assert not has_inline_tests('// #[cfg(test)] is below\n#[cfg(feature = "x")]\n')


def test_rust_tests_added_compares_with_the_parent() -> None:
    one = b"#[cfg(test)]\nmod t {\n#[test]\nfn a() {}\n}\n"
    two = one + b"#[test]\nfn b() {}\n"
    assert rust_tests_added(two, one)
    assert rust_tests_added(one, b"")
    assert not rust_tests_added(one, one)
    assert not rust_tests_added(one, two)


def test_detect_by_language() -> None:
    header = b"// @generated\n"
    assert detect(None, header) == ()
    assert detect(Language.GO, header) == (GENERATED_HEADER,)
    minified = b"var a=1;" * 100
    assert detect(Language.JAVASCRIPT, minified) == (MINIFIED,)
    assert detect(Language.TYPESCRIPT, minified) == ()
    inline = b"// @generated\n#[cfg(test)]\nmod t {}\n"
    assert detect(Language.RUST, inline) == (GENERATED_HEADER, RUST_INLINE_TESTS)
    assert detect(Language.PYTHON, b"#[cfg(test)]\n") == ()
    assert detect_path("src/lib.rs", b"#[cfg(test)]\n") == (RUST_INLINE_TESTS,)
    assert detect_path("README.md", header) == ()


def test_detect_ignores_bytes_after_the_limit_and_bad_utf8() -> None:
    late = b"x" * MAX_CONTENT + b"\n#[cfg(test)]\n"
    assert detect(Language.RUST, late) == ()
    assert detect(Language.GO, b"// @generated \xff\xfe\n") == (GENERATED_HEADER,)


def test_every_signal_is_documented() -> None:
    assert all(description.isascii() and description for description in SIGNALS.values())
