from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from commitminer.classify import RULES, Category, Rule
from commitminer.cli import app
from commitminer.ruletable import classify_file, render_rules_markdown
from gitrepo import GitRepo, lines

runner = CliRunner()
ROOT = Path(__file__).resolve().parent.parent
SAMPLE = ROOT / "examples" / "classify"
SAMPLE_PATHS = [
    "src/lib.rs",
    "internal/kind/kind_string.go",
    "web/static/bundle.js",
    "web/src/app.test.ts",
    "vendor/github.com/acme/left/left.go",
    "fixtures/percent.json",
    "tools/cli/main.go",
    "Cargo.lock",
    "README.md",
]


def test_classify_the_sample_tree_golden() -> None:
    result = runner.invoke(app, ["classify", "--root", str(SAMPLE), *SAMPLE_PATHS])
    assert result.exit_code == 0, result.output
    table = result.stdout.split("\n\nrules used:\n")[0]
    assert table.splitlines() == [
        "category   rule               path",
        "source     rust-inline-tests  src/lib.rs  [rust-inline-tests]",
        "generated  generated-header   internal/kind/kind_string.go  [generated-header]",
        "generated  minified-content   web/static/bundle.js  [minified]",
        "test       js-test-file       web/src/app.test.ts",
        "vendored   vendored-dir       vendor/github.com/acme/left/left.go",
        "test       fixtures-dir       fixtures/percent.json",
        "source     go-source          tools/cli/main.go",
        "generated  lockfile           Cargo.lock *",
        "docs       docs-file          README.md",
        "* not a file under the root: classified by path only",
    ]
    assert "  fixtures-dir       this project keeps test inputs" in result.stdout


def test_classify_json_and_no_content() -> None:
    result = runner.invoke(
        app,
        ["classify", "--root", str(SAMPLE), "--json", "--no-content", "src/lib.rs", "x/y.bin"],
    )
    assert result.exit_code == 0, result.output
    first, second = (json.loads(line) for line in result.stdout.splitlines())
    assert first == {
        "category": "source",
        "content_read": False,
        "language": "rust",
        "path": "src/lib.rs",
        "rule": "rust-source",
        "signals": [],
    }
    assert second["rule"] == "fallback"
    assert second["language"] is None
    text = runner.invoke(app, ["classify", "--root", str(SAMPLE), "--no-content", "src/lib.rs"])
    assert "content not read (--no-content)" in text.stdout
    assert "rust-source" in text.stdout


def test_classify_uses_builtin_rules_without_a_config(tmp_path: Path) -> None:
    (tmp_path / "fixtures").mkdir()
    (tmp_path / "fixtures" / "a.json").write_text("{}", encoding="utf-8")
    result = runner.invoke(app, ["classify", "--root", str(tmp_path), "fixtures/a.json"])
    assert result.exit_code == 0, result.output
    assert "other      fallback  fixtures/a.json" in result.stdout
    assert "  fallback  no rule matched" in result.stdout


def test_classify_explicit_config_and_absolute_paths(tmp_path: Path) -> None:
    config = tmp_path / "rules.toml"
    config.write_text(
        '[[classify.rules]]\nid = "proto"\ncategory = "config"\nnames = ["*.proto"]\n'
        'rationale = "interface definitions"\n',
        encoding="utf-8",
    )
    target = tmp_path / "api" / "v1.proto"
    result = runner.invoke(
        app, ["classify", "--root", str(tmp_path), "--config", str(config), str(target)]
    )
    assert result.exit_code == 0, result.output
    assert "config     proto  api/v1.proto *" in result.stdout


def test_classify_rejects_directories_and_outside_paths(tmp_path: Path) -> None:
    (tmp_path / "src").mkdir()
    result = runner.invoke(app, ["classify", "--root", str(tmp_path), "src"])
    assert result.exit_code == 2
    assert "src is a directory" in result.stderr
    outside = runner.invoke(app, ["classify", "--root", str(tmp_path / "src"), str(tmp_path)])
    assert outside.exit_code == 2
    assert "is outside the root" in outside.stderr


def test_classify_reports_config_errors(tmp_path: Path) -> None:
    (tmp_path / "commitminer.toml").write_text("[classify]\nbogus = 1\n", encoding="utf-8")
    result = runner.invoke(app, ["classify", "--root", str(tmp_path), "a.py"])
    assert result.exit_code == 2
    assert "unknown key 'bogus'" in result.stderr


def test_classify_file_reads_only_regular_files(tmp_path: Path) -> None:
    (tmp_path / "gen.go").write_bytes(b"// Code generated by x. DO NOT EDIT.\npackage p\n")
    verdict = classify_file(tmp_path, "gen.go", RULES)
    assert (verdict.rule_id, verdict.read, verdict.signals) == (
        "generated-header",
        True,
        ("generated-header",),
    )
    assert classify_file(tmp_path, "gen.go", RULES, content=False).rule_id == "go-source"
    assert classify_file(tmp_path, "nope.go", RULES).read is False


def test_rules_command_lists_the_effective_table() -> None:
    result = runner.invoke(app, ["rules", "--root", str(SAMPLE)])
    assert result.exit_code == 0, result.output
    out = result.stdout.splitlines()
    assert out[0] == (
        f"config: {SAMPLE / 'commitminer.toml'}: 1 custom rule, 1 built-in rule disabled"
    )
    assert out[1] == " 1. fixtures-dir -> test [any]  (commitminer.toml)"
    assert " 2. vendored-dir -> vendored [any]" in out
    assert not any("tooling-dir" in line for line in out)
    assert "    name: *Test.java, *Tests.java, *TestCase.java, *IT.java, " in result.stdout
    assert out[-1] == "    no rule matched -> other (fallback)"


def test_rules_without_config(tmp_path: Path) -> None:
    result = runner.invoke(app, ["rules", "--root", str(tmp_path)])
    assert result.exit_code == 0
    assert result.stdout.startswith(" 1. vendored-dir -> vendored [any]\n")
    assert f"{len(RULES)}. docs-name -> docs [any]" in result.stdout


def test_docs_rules_md_matches_the_code() -> None:
    result = runner.invoke(app, ["rules", "--markdown", "--root", str(ROOT / "docs")])
    assert result.exit_code == 0
    assert result.stdout == render_rules_markdown(RULES) + "\n"
    committed = (ROOT / "docs" / "rules.md").read_text(encoding="utf-8")
    assert committed.endswith("\n" + result.stdout), "run make rules-doc"


def test_markdown_escapes_pipes() -> None:
    piped = Rule("piped", Category.TEST, "name", ("a",), "one | two")
    assert "one \\| two" in render_rules_markdown([piped])


@pytest.fixture
def fixtures_repo(git_repo: GitRepo) -> GitRepo:
    """A repository whose tests keep data in fixtures/, which only the config knows."""
    git_repo.commit("Initial", {"src/pkg/core.py": lines(10)})
    git_repo.commit(
        "Fix rounding (fixes #3)",
        {"src/pkg/core.py": lines(10) + "fixed\n", "fixtures/round.json": lines(6)},
    )
    return git_repo


def test_mine_uses_the_repository_config(fixtures_repo: GitRepo, tmp_path: Path) -> None:
    before = runner.invoke(app, ["mine", str(fixtures_repo.root), "--explain", "0"])
    assert before.exit_code == 0, before.output
    assert "0 candidates" in before.stdout
    (fixtures_repo.root / "commitminer.toml").write_text(
        '[[classify.rules]]\nid = "fixtures-dir"\ncategory = "test"\ndirs = ["fixtures"]\n'
        'rationale = "test data"\n',
        encoding="utf-8",
    )
    after = runner.invoke(app, ["mine", str(fixtures_repo.root), "--explain", "0"])
    assert after.exit_code == 0, after.output
    first, second = after.stdout.splitlines()[:2]
    assert first == (
        f"config: {fixtures_repo.root / 'commitminer.toml'}: "
        "1 custom rule, 0 built-in rules disabled"
    )
    assert "1 candidates" in second
    recording = tmp_path / "h.jsonl"
    assert (
        runner.invoke(app, ["record", str(fixtures_repo.root), "--out", str(recording)]).exit_code
        == 0
    )
    replay = runner.invoke(app, ["mine", "--history", str(recording), "--explain", "0"])
    assert "0 candidates" in replay.stdout
    explicit = runner.invoke(
        app,
        [
            "mine",
            "--history",
            str(recording),
            "--config",
            str(fixtures_repo.root / "commitminer.toml"),
            "--explain",
            "0",
        ],
    )
    assert "1 candidates" in explicit.stdout


def test_mine_reports_a_bad_config(fixtures_repo: GitRepo) -> None:
    (fixtures_repo.root / "commitminer.toml").write_text("oops = [\n", encoding="utf-8")
    result = runner.invoke(app, ["mine", str(fixtures_repo.root)])
    assert result.exit_code == 2
    assert "invalid TOML" in result.stderr


def test_mine_a_rust_repository_with_inline_tests(git_repo: GitRepo, tmp_path: Path) -> None:
    body = "pub fn half(n: u32) -> u32 {\n    n / 2\n}\n"
    tests = (
        "\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn halves() {\n"
        "        assert_eq!(super::half(4), 2);\n    }\n"
    )
    git_repo.commit("Add half", {"Cargo.toml": "[package]\n", "src/lib.rs": body + tests + "}\n"})
    fixed = body.replace("n / 2", "n.div_ceil(2)")
    extra = "\n    #[test]\n    fn rounds_up() {\n        assert_eq!(super::half(3), 2);\n    }\n"
    git_repo.commit("Round half up (fixes #7)", {"src/lib.rs": fixed + tests + extra + "}\n"})
    out = tmp_path / "rust.jsonl"
    result = runner.invoke(app, ["mine", str(git_repo.root), "--out", str(out), "--explain", "0"])
    assert result.exit_code == 0, result.output
    assert "2 candidates" in result.stdout.splitlines()[0]
    best = json.loads(out.read_text(encoding="ascii").splitlines()[1])  # after the run record
    assert best["subject"] == "Round half up (fixes #7)"
    assert best["fail_to_pass"] == ["src/lib.rs::tests::rounds_up"]
    assert best["inline_test_files"] == ["src/lib.rs"]
    paths = runner.invoke(app, ["mine", str(git_repo.root), "--no-content", "--explain", "0"])
    assert paths.stdout.splitlines()[0].endswith("0 candidates, 2 rejected (no-test 2)")


def test_a_bad_glob_in_the_config_is_a_plain_error(tmp_path: Path) -> None:
    (tmp_path / "commitminer.toml").write_text(
        '[[classify.rules]]\nid = "fx"\ncategory = "test"\nnames = ["[z-a]*.json"]\n'
        'rationale = "typo"\n',
        encoding="utf-8",
    )
    for args in (["classify", "a.json"], ["rules"]):
        result = runner.invoke(app, [*args, "--root", str(tmp_path)])
        assert result.exit_code == 2
        assert "Traceback" not in result.output
        assert "classify.rules[0]: rule fx: '[z-a]*.json': empty character range z-a" in (
            result.stderr
        )
