"""Table-driven tests for the classifier: every rule has positive and negative examples.

A positive example is a path (with optional file content, from which content
signals are detected) that the rule must decide. A negative example looks like
the rule's target but must be decided by a different rule. Adding a rule to the
table without examples here fails ``test_every_rule_has_examples``.
"""

from __future__ import annotations

from dataclasses import dataclass

import pytest

from commitminer.classify import (
    FALLBACK_RULE,
    RULES,
    Category,
    Classification,
    Rule,
    Target,
    classify,
    match,
)
from commitminer.signals import detect_path

C = Category

GO_GENERATED = "// Code generated by stringer -type=Kind; DO NOT EDIT.\n\npackage kind\n"
PY_GENERATED = "# -*- coding: utf-8 -*-\n# Generated by the table builder.  DO NOT EDIT!\nX = 1\n"
TS_GENERATED = "/* eslint-disable */\n// @generated by schema-to-ts\nexport type Id = string;\n"
JAVA_GENERATED = "/*\n * This file is auto-generated from api.yaml.\n */\npackage api;\n"
MINIFIED_JS = "!function(){" + "var a=1,b=2;" * 60 + "}();\n"
PLAIN_JS = "export function add(a, b) {\n  return a + b;\n}\n" * 20
LONG_TS = "export const table = [" + "1, " * 300 + "];\n"
RUST_WITH_TESTS = (
    "pub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\n"
    "#[cfg(test)]\nmod tests {\n    #[test]\n    fn adds() {\n"
    "        assert_eq!(super::add(1, 2), 3);\n    }\n}\n"
)
RUST_PLAIN = "pub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n"


@dataclass(frozen=True)
class Example:
    path: str
    category: Category
    rule_id: str
    content: str | None = None

    def classify(self) -> Classification:
        signals = detect_path(self.path, self.content.encode()) if self.content else ()
        return classify(self.path, signals=signals)


def ex(path: str, category: Category, rule_id: str, content: str | None = None) -> Example:
    return Example(path, category, rule_id, content)


# rule id -> (positive examples, negative examples)
EXAMPLES: dict[str, tuple[list[Example], list[Example]]] = {
    "vendored-dir": (
        [
            ex("vendor/github.com/pkg/errors/errors.go", C.VENDORED, "vendored-dir"),
            ex("web/node_modules/left-pad/index.js", C.VENDORED, "vendored-dir"),
            ex("third_party/zlib/tests/test_inflate.py", C.VENDORED, "vendored-dir"),
            ex("vendor/serde/src/lib.rs", C.VENDORED, "vendored-dir", RUST_WITH_TESTS),
        ],
        [
            ex("src/vendors/api.py", C.SOURCE, "py-source"),
            ex("pkg/vendor.go", C.SOURCE, "go-source"),
        ],
    ),
    "java-test-dir": (
        [
            ex("src/test/java/com/example/ParserTest.java", C.TEST, "java-test-dir"),
            ex("core/src/test/resources/fixture.json", C.TEST, "java-test-dir"),
            ex("lib/src/testFixtures/java/Fakes.java", C.TEST, "java-test-dir"),
            ex("app/src/integrationTest/kotlin/Smoke.kt", C.TEST, "java-test-dir"),
        ],
        [
            ex("src/main/java/com/example/Parser.java", C.SOURCE, "java-main-dir"),
            ex("src/testing/java/Helper.java", C.SOURCE, "java-source"),
        ],
    ),
    "test-dir": (
        [
            ex("tests/test_parser.py", C.TEST, "test-dir"),
            ex("tests/data/valid/array.toml", C.TEST, "test-dir"),
            ex("src/pkg/test/helpers.py", C.TEST, "test-dir"),
            ex("Tests/README.md", C.TEST, "test-dir"),
            ex("crates/core/tests/parse.rs", C.TEST, "test-dir"),
            ex("test/index.js", C.TEST, "test-dir"),
            ex("tests/golden/out.pb.go", C.TEST, "test-dir"),
        ],
        [
            ex("src/pkg/testing.py", C.SOURCE, "py-source"),
            ex("src/latest/mod.rs", C.SOURCE, "rust-source"),
            ex("src/contest/index.ts", C.SOURCE, "js-source"),
        ],
    ),
    "js-test-dir": (
        [
            ex("src/__tests__/app.ts", C.TEST, "js-test-dir"),
            ex("src/__snapshots__/app.test.ts.snap", C.TEST, "js-test-dir"),
            ex("src/__mocks__/fs.js", C.TEST, "js-test-dir"),
        ],
        [
            ex("src/__test__/app.ts", C.SOURCE, "js-source"),
            ex("src/tests_helper.ts", C.SOURCE, "js-source"),
        ],
    ),
    "go-testdata-dir": (
        [
            ex("internal/parse/testdata/golden.go", C.TEST, "go-testdata-dir", GO_GENERATED),
            ex("testdata/input.txt", C.TEST, "go-testdata-dir"),
        ],
        [
            ex("internal/testdatagen/gen.go", C.SOURCE, "go-source"),
            ex("internal/data/test.go", C.SOURCE, "go-source"),
        ],
    ),
    "lockfile": (
        [
            ex("Cargo.lock", C.GENERATED, "lockfile"),
            ex("package-lock.json", C.GENERATED, "lockfile"),
            ex("web/yarn.lock", C.GENERATED, "lockfile"),
            ex("pnpm-lock.yaml", C.GENERATED, "lockfile"),
            ex("go.sum", C.GENERATED, "lockfile"),
            ex("uv.lock", C.GENERATED, "lockfile"),
        ],
        [
            ex("package.json", C.CONFIG, "js-config-file"),
            ex("src/lock.rs", C.SOURCE, "rust-source"),
            ex("internal/sum.go", C.SOURCE, "go-source"),
        ],
    ),
    "generated-name": (
        [
            ex("api/v1/service.pb.go", C.GENERATED, "generated-name"),
            ex("proto/msg_pb2.py", C.GENERATED, "generated-name"),
            ex("proto/msg_pb2_grpc.py", C.GENERATED, "generated-name"),
            ex("apis/zz_generated.deepcopy.go", C.GENERATED, "generated-name"),
            ex("src/schema.generated.ts", C.GENERATED, "generated-name"),
        ],
        [
            ex("api/v1/service.go", C.SOURCE, "go-source"),
            ex("proto/msg_pb.py", C.SOURCE, "py-source"),
            ex("src/generator.ts", C.SOURCE, "js-source"),
        ],
    ),
    "minified-name": (
        [
            ex("static/app.min.js", C.GENERATED, "minified-name"),
            ex("static/app.js.map", C.GENERATED, "minified-name"),
            ex("static/site.min.css", C.GENERATED, "minified-name"),
        ],
        [
            ex("static/admin.js", C.SOURCE, "js-source", PLAIN_JS),
            ex("src/math.min.ts", C.SOURCE, "js-source"),
        ],
    ),
    "generated-header": (
        [
            ex("internal/kind/kind_string.go", C.GENERATED, "generated-header", GO_GENERATED),
            ex("src/pkg/tables.py", C.GENERATED, "generated-header", PY_GENERATED),
            ex("src/api/types.ts", C.GENERATED, "generated-header", TS_GENERATED),
            ex("src/main/java/api/Model.java", C.GENERATED, "generated-header", JAVA_GENERATED),
            ex("kind_test.go", C.GENERATED, "generated-header", GO_GENERATED),
        ],
        [
            ex("src/pkg/gen.py", C.SOURCE, "py-source", "# Generate the tables on import\nX=1\n"),
            ex("src/pkg/msg.py", C.SOURCE, "py-source", 'MARK = "@generated"\n'),
            ex("src/pkg/late.py", C.SOURCE, "py-source", "x = 1\n" * 30 + "# @generated\n"),
            ex("docs.md", C.DOCS, "docs-file", "# Code generated by tool. DO NOT EDIT.\n"),
        ],
    ),
    "minified-content": (
        [
            ex("static/vendor-bundle.js", C.GENERATED, "minified-content", MINIFIED_JS),
            ex("lib/index.cjs", C.GENERATED, "minified-content", MINIFIED_JS),
        ],
        [
            ex("static/app.js", C.SOURCE, "js-source", PLAIN_JS),
            ex("src/table.ts", C.SOURCE, "js-source", LONG_TS),
            ex("static/tiny.js", C.SOURCE, "js-source", "module.exports=require('./a');"),
        ],
    ),
    "js-dist-dir": (
        [
            ex("dist/index.js", C.GENERATED, "js-dist-dir", PLAIN_JS),
            ex("packages/core/dist/index.d.ts", C.GENERATED, "js-dist-dir"),
        ],
        [
            ex("dist/README.md", C.DOCS, "docs-file"),
            ex("dist/setup_helpers.py", C.SOURCE, "py-source"),
            ex("src/distance.ts", C.SOURCE, "js-source"),
        ],
    ),
    "py-test-file": (
        [
            ex("src/pkg/test_utils.py", C.TEST, "py-test-file"),
            ex("pkg/parser_test.py", C.TEST, "py-test-file"),
            ex("conftest.py", C.TEST, "py-test-file"),
            ex("pkg/tests.py", C.TEST, "py-test-file"),
        ],
        [
            ex("src/pkg/testing.py", C.SOURCE, "py-source"),
            ex("src/pkg/contest.py", C.SOURCE, "py-source"),
            ex("src/pkg/test_utils.rs", C.SOURCE, "rust-source"),
        ],
    ),
    "js-test-file": (
        [
            ex("src/app.test.ts", C.TEST, "js-test-file"),
            ex("lib/parse.spec.js", C.TEST, "js-test-file"),
            ex("src/Button.test.tsx", C.TEST, "js-test-file"),
            ex("src/util.spec.mjs", C.TEST, "js-test-file"),
        ],
        [
            ex("src/test-utils.ts", C.SOURCE, "js-source"),
            ex("src/app.testing.ts", C.SOURCE, "js-source"),
            ex("src/app.test.snap", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "go-test-file": (
        [
            ex("parse_test.go", C.TEST, "go-test-file"),
            ex("internal/lexer/lexer_test.go", C.TEST, "go-test-file"),
        ],
        [
            ex("parse_testing.go", C.SOURCE, "go-source"),
            ex("testutil.go", C.SOURCE, "go-source"),
        ],
    ),
    "java-test-file": (
        [
            ex("app/ParserTest.java", C.TEST, "java-test-file"),
            ex("app/ParserTests.java", C.TEST, "java-test-file"),
            ex("app/ParserIT.java", C.TEST, "java-test-file"),
            ex("app/TestParser.java", C.TEST, "java-test-file"),
            ex("app/ParserTestCase.java", C.TEST, "java-test-file"),
        ],
        [
            ex("app/Latest.java", C.SOURCE, "java-source"),
            ex("app/Testable.java", C.SOURCE, "java-source"),
            ex("app/parsertest.java", C.SOURCE, "java-source"),
        ],
    ),
    "rust-test-file": (
        [
            ex("src/tests.rs", C.TEST, "rust-test-file"),
            ex("src/parser/parse_tests.rs", C.TEST, "rust-test-file"),
        ],
        [
            ex("src/testing.rs", C.SOURCE, "rust-source"),
            ex("src/tests.py", C.TEST, "py-test-file"),
            ex("src/tests_support.rs", C.SOURCE, "rust-source"),
        ],
    ),
    "java-main-dir": (
        [
            ex("src/main/java/com/example/Parser.java", C.SOURCE, "java-main-dir"),
            ex("core/src/main/java/org/acme/tools/Cli.java", C.SOURCE, "java-main-dir"),
            ex("src/main/java/org/acme/docs/Render.java", C.SOURCE, "java-main-dir"),
        ],
        [
            ex("src/main/java/com/example/ParserTest.java", C.TEST, "java-test-file"),
            ex("src/main/resources/app.properties", C.OTHER, FALLBACK_RULE),
            ex("src/main/java/api/Model.java", C.GENERATED, "generated-header", JAVA_GENERATED),
        ],
    ),
    "ci-config": (
        [
            ex(".github/workflows/ci.yml", C.CONFIG, "ci-config"),
            ex(".travis.yml", C.CONFIG, "ci-config"),
            ex(".gitlab-ci.yml", C.CONFIG, "ci-config"),
            ex("azure-pipelines.yml", C.CONFIG, "ci-config"),
        ],
        [
            ex("docs/github.md", C.DOCS, "docs-dir"),
            ex("src/ci.py", C.SOURCE, "py-source"),
            ex("sub/.travis.yml", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "build-config": (
        [
            ex("Makefile", C.CONFIG, "build-config"),
            ex("docker/Dockerfile", C.CONFIG, "build-config"),
            ex(".gitignore", C.CONFIG, "build-config"),
            ex("setup.cfg", C.CONFIG, "build-config"),
            ex("tox.ini", C.CONFIG, "build-config"),
        ],
        [
            ex("src/makefile.py", C.SOURCE, "py-source"),
            ex("Dockerfile.md", C.DOCS, "docs-file"),
        ],
    ),
    "py-config-file": (
        [
            ex("pyproject.toml", C.CONFIG, "py-config-file"),
            ex("setup.py", C.CONFIG, "py-config-file"),
            ex("requirements-dev.txt", C.CONFIG, "py-config-file"),
            ex("noxfile.py", C.CONFIG, "py-config-file"),
        ],
        [
            ex("src/pkg/setup_utils.py", C.SOURCE, "py-source"),
            ex("requirements.md", C.DOCS, "docs-file"),
        ],
    ),
    "rust-config-file": (
        [
            ex("Cargo.toml", C.CONFIG, "rust-config-file"),
            ex("crates/core/Cargo.toml", C.CONFIG, "rust-config-file"),
            ex("rust-toolchain.toml", C.CONFIG, "rust-config-file"),
            ex("rustfmt.toml", C.CONFIG, "rust-config-file"),
        ],
        [
            ex("src/cargo.rs", C.SOURCE, "rust-source"),
            ex("Cargo.toml.orig", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "js-config-file": (
        [
            ex("package.json", C.CONFIG, "js-config-file"),
            ex("tsconfig.base.json", C.CONFIG, "js-config-file"),
            ex("jest.config.ts", C.CONFIG, "js-config-file"),
            ex(".eslintrc.cjs", C.CONFIG, "js-config-file"),
            ex("vite.config.mts", C.CONFIG, "js-config-file"),
            ex("deno.jsonc", C.CONFIG, "js-config-file"),
        ],
        [
            ex("src/config.ts", C.SOURCE, "js-source"),
            ex("src/package.ts", C.SOURCE, "js-source"),
        ],
    ),
    "go-config-file": (
        [
            ex("go.mod", C.CONFIG, "go-config-file"),
            ex("go.work", C.CONFIG, "go-config-file"),
            ex(".golangci.yml", C.CONFIG, "go-config-file"),
        ],
        [
            ex("mod.go", C.SOURCE, "go-source"),
            ex("go.sum", C.GENERATED, "lockfile"),
        ],
    ),
    "java-config-file": (
        [
            ex("pom.xml", C.CONFIG, "java-config-file"),
            ex("app/build.gradle.kts", C.CONFIG, "java-config-file"),
            ex("settings.gradle", C.CONFIG, "java-config-file"),
            ex("gradlew", C.CONFIG, "java-config-file"),
            ex("gradle/wrapper/gradle-wrapper.properties", C.CONFIG, "java-config-file"),
        ],
        [
            ex("src/main/java/Build.java", C.SOURCE, "java-main-dir"),
            ex("gradle.md", C.DOCS, "docs-file"),
        ],
    ),
    "docs-dir": (
        [
            ex("docs/conf.py", C.DOCS, "docs-dir"),
            ex("doc/usage.rst", C.DOCS, "docs-dir"),
            ex("documentation/api.ts", C.DOCS, "docs-dir"),
        ],
        [
            ex("src/pkg/docstrings.py", C.SOURCE, "py-source"),
            ex("src/docs.rs", C.SOURCE, "rust-source"),
        ],
    ),
    "tooling-dir": (
        [
            ex("benchmark/run.py", C.OTHER, "tooling-dir"),
            ex("benches/parse.rs", C.OTHER, "tooling-dir", RUST_WITH_TESTS),
            ex("scripts/release.py", C.OTHER, "tooling-dir"),
            ex("examples/demo/main.go", C.OTHER, "tooling-dir"),
            ex("fuzz/fuzz_targets/parse.rs", C.OTHER, "tooling-dir"),
        ],
        [
            ex("src/benchmarks.py", C.SOURCE, "py-source"),
            ex("src/scripting/eval.rs", C.SOURCE, "rust-source"),
        ],
    ),
    "rust-inline-tests": (
        [
            ex("src/lib.rs", C.SOURCE, "rust-inline-tests", RUST_WITH_TESTS),
            ex(
                "src/io.rs",
                C.SOURCE,
                "rust-inline-tests",
                "#[cfg(all(test, unix))]\nmod tests {}\n",
            ),
        ],
        [
            ex("src/lib.rs", C.SOURCE, "rust-source", RUST_PLAIN),
            ex("src/lib.py", C.SOURCE, "py-source", RUST_WITH_TESTS),
            ex("src/cfg.rs", C.SOURCE, "rust-source", "// see #[cfg(test)] below\nfn f() {}\n"),
        ],
    ),
    "py-source": (
        [
            ex("src/pkg/parser.py", C.SOURCE, "py-source"),
            ex("pkg/__init__.pyi", C.SOURCE, "py-source"),
            ex("pkg/_speedups.pyx", C.SOURCE, "py-source"),
            ex("src\\pkg\\win.py", C.SOURCE, "py-source"),
            ex("./src/pkg/history.py", C.SOURCE, "py-source"),
            ex("src/pkg/license.py", C.SOURCE, "py-source"),
        ],
        [
            ex("src/pkg/py.typed", C.OTHER, FALLBACK_RULE),
            ex("src/pkg/parser.pyc", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "rust-source": (
        [
            ex("src/parser.rs", C.SOURCE, "rust-source", RUST_PLAIN),
            ex("crates/core/src/main.rs", C.SOURCE, "rust-source"),
        ],
        [
            ex("src/parser.rst", C.DOCS, "docs-file"),
            ex("src/parser.rs.orig", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "js-source": (
        [
            ex("src/index.ts", C.SOURCE, "js-source"),
            ex("lib/util.mjs", C.SOURCE, "js-source"),
            ex("src/App.tsx", C.SOURCE, "js-source"),
            ex("index.d.ts", C.SOURCE, "js-source"),
        ],
        [
            ex("src/index.json", C.OTHER, FALLBACK_RULE),
            ex("src/.js", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "go-source": (
        [
            ex("cmd/tool/main.go", C.SOURCE, "go-source"),
            ex("internal/lexer/lexer.go", C.SOURCE, "go-source"),
        ],
        [
            ex("main.go.tmpl", C.OTHER, FALLBACK_RULE),
            ex("go.md", C.DOCS, "docs-file"),
        ],
    ),
    "java-source": (
        [
            ex("app/Contest.java", C.SOURCE, "java-source"),
            ex("Parser.java", C.SOURCE, "java-source"),
        ],
        [
            ex("tools/Parser.java", C.OTHER, "tooling-dir"),
            ex("Parser.class", C.OTHER, FALLBACK_RULE),
            ex("Parser.jar", C.OTHER, FALLBACK_RULE),
        ],
    ),
    "docs-file": (
        [
            ex("README.md", C.DOCS, "docs-file"),
            ex("CHANGELOG.md", C.DOCS, "docs-file"),
            ex("src/pkg/notes.txt", C.DOCS, "docs-file"),
            ex("guide.adoc", C.DOCS, "docs-file"),
            ex("benchmark/README.md", C.DOCS, "docs-file"),
        ],
        [
            ex("requirements.txt", C.CONFIG, "py-config-file"),
            ex("src/markdown.py", C.SOURCE, "py-source"),
            ex("README", C.DOCS, "docs-name"),
        ],
    ),
    "docs-name": (
        [
            ex("LICENSE", C.DOCS, "docs-name"),
            ex("LICENSE-APACHE", C.DOCS, "docs-name"),
            ex("CHANGELOG", C.DOCS, "docs-name"),
            ex("AUTHORS", C.DOCS, "docs-name"),
        ],
        [
            ex("src/license.rs", C.SOURCE, "rust-source"),
            ex("src/readme.ts", C.SOURCE, "js-source"),
            ex("src/pkg/history.py", C.SOURCE, "py-source"),
            ex("benchmark/LICENSE", C.OTHER, "tooling-dir"),
        ],
    ),
    FALLBACK_RULE: (
        [
            ex("assets/logo.png", C.OTHER, FALLBACK_RULE),
            ex("src/pkg/py.typed", C.OTHER, FALLBACK_RULE),
            ex("data/table.json", C.OTHER, FALLBACK_RULE),
        ],
        [
            ex("assets/logo.md", C.DOCS, "docs-file"),
        ],
    ),
}

ALL_EXAMPLES = [
    pytest.param(example, id=f"{rule_id}:{'+' if positive else '-'}:{example.path}")
    for rule_id, (positives, negatives) in EXAMPLES.items()
    for positive, group in ((True, positives), (False, negatives))
    for example in group
]


@pytest.mark.parametrize("example", ALL_EXAMPLES)
def test_example_is_classified_as_expected(example: Example) -> None:
    assert example.classify() == Classification(example.category, example.rule_id)


def test_every_rule_has_examples() -> None:
    table_ids = [rule.rule_id for rule in RULES] + [FALLBACK_RULE]
    assert sorted(EXAMPLES) == sorted(table_ids)
    for rule_id, (positives, negatives) in EXAMPLES.items():
        assert positives, f"{rule_id} has no positive example"
        assert negatives, f"{rule_id} has no negative example"
        assert all(e.rule_id == rule_id for e in positives), rule_id
        assert all(e.rule_id != rule_id for e in negatives), rule_id


def test_positive_examples_carry_the_rule_category() -> None:
    by_id = {rule.rule_id: rule.category for rule in RULES}
    for rule_id, (positives, _) in EXAMPLES.items():
        for example in positives:
            assert example.category == by_id.get(rule_id, Category.OTHER), example


def test_rule_ids_are_unique() -> None:
    ids = [rule.rule_id for rule in RULES]
    assert len(ids) == len(set(ids))
    assert FALLBACK_RULE not in ids


def test_every_rule_is_reachable_and_has_a_rationale() -> None:
    for rule in RULES:
        assert rule.rationale.strip()
        assert rule.rationale.isascii()


def test_empty_table_falls_back() -> None:
    assert classify("tests/test_x.py", rules=()) == Classification(Category.OTHER, FALLBACK_RULE)
    assert match("tests/test_x.py", rules=()) is None


def test_match_returns_the_rule() -> None:
    rule = match("src/lib.rs", signals=["rust-inline-tests"])
    assert rule is not None
    assert rule.rule_id == "rust-inline-tests"
    assert rule.languages_label == "rust"
    first = match("vendor/x.go")
    assert first is not None
    assert first.languages_label == "any"


def test_signals_only_count_for_their_languages() -> None:
    # A signal attached to a file of another language does not trigger the rule.
    assert classify("src/app.py", signals=["minified"]).rule_id == "py-source"
    assert classify("src/app.js", signals=["minified"]).rule_id == "minified-content"


def test_target_normalises_paths() -> None:
    target = Target.of(".\\src/./pkg\\mod.py", ["x"])
    assert target.path == "src/./pkg/mod.py"
    assert target.parts == ("src", ".", "pkg", "mod.py")
    assert target.directories == ("src", ".", "pkg")
    assert target.name == "mod.py"
    assert target.signals == frozenset({"x"})
    assert Target.of("././a.go").path == "a.go"


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"rule_id": "Bad Id"}, "use lower-case"),
        ({"kind": "glob"}, "unknown kind"),
        ({"patterns": ()}, "at least one"),
        ({"patterns": ("",)}, "at least one"),
        ({"kind": "signal", "patterns": ("nope",)}, "unknown signal"),
        ({"rationale": " "}, "needs a rationale"),
        ({"patterns": ("[z-a]*.json",)}, "rule ok: '.*': empty character range z-a"),
        ({"patterns": ("src/fixtures",)}, "cannot contain '/'"),
        ({"kind": "name", "patterns": ("data/*.json",)}, "cannot contain '/'"),
        ({"kind": "path", "patterns": ("/src/**",)}, "relative to the root"),
        ({"kind": "path", "patterns": ("src//x",)}, "empty path segment"),
        ({"patterns": ("a\\b",)}, "backslash"),
    ],
)
def test_rule_validation(kwargs: dict[str, object], message: str) -> None:
    fields: dict[str, object] = {
        "rule_id": "ok",
        "category": Category.TEST,
        "kind": "dir",
        "patterns": ("x",),
        "rationale": "why",
    }
    fields.update(kwargs)
    with pytest.raises(ValueError, match=message):
        Rule(**fields)  # type: ignore[arg-type]


def test_path_rules_match_whole_components() -> None:
    rule = Rule("gen", Category.GENERATED, "path", ("gen/**", "**/api/*.json"), "why")
    assert rule.matches(Target.of("gen/a/b.go"))
    assert rule.matches(Target.of("x/y/api/v1.json"))
    assert rule.matches(Target.of("api/v1.json"))
    assert not rule.matches(Target.of("gen"))
    assert not rule.matches(Target.of("generated/a.go"))
    assert not rule.matches(Target.of("api/v1/x.json"))
