"""Content signals read during a walk: git cat-file --batch and per-file signals."""

from __future__ import annotations

import io
import subprocess
from pathlib import Path

import pytest

from commitminer.gitlog import BlobReader, GitError, file_details, walk
from commitminer.models import Commit, FileChange
from commitminer.scoring import mine
from gitrepo import GitRepo

LIB_V1 = (
    "pub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\n"
    "#[cfg(test)]\nmod tests {\n    #[test]\n    fn adds() {\n"
    "        assert_eq!(super::add(1, 2), 3);\n    }\n}\n"
)
LIB_V2 = (
    "pub fn add(a: i32, b: i32) -> i32 {\n    a.saturating_add(b)\n}\n\n"
    "#[cfg(test)]\nmod tests {\n    #[test]\n    fn adds() {\n"
    "        assert_eq!(super::add(1, 2), 3);\n    }\n\n"
    "    #[test]\n    fn saturates() {\n"
    "        assert_eq!(super::add(i32::MAX, 1), i32::MAX);\n    }\n}\n"
)
GENERATED_GO = "// Code generated by stringer; DO NOT EDIT.\n\npackage kind\n"
MINIFIED_JS = "(()=>{" + "var a=function(b){return b*2};" * 30 + "})();\n"


def signals_by_path(commit: Commit) -> dict[str, tuple[str, ...]]:
    return {f.path: f.signals for f in commit.files}


def test_walk_reads_content_signals(git_repo: GitRepo) -> None:
    git_repo.commit(
        "Add library",
        {
            "src/lib.rs": LIB_V1,
            "internal/kind/kind_string.go": GENERATED_GO,
            "web/bundle.js": MINIFIED_JS,
            "web/logo.js": b"\x00\x01binary\x00",
            "README.md": "// @generated\n",
        },
    )
    git_repo.commit("Saturate on overflow", {"src/lib.rs": LIB_V2})
    git_repo.commit(
        "Tweak code only", {"src/lib.rs": LIB_V2.replace("saturating_add", "wrapping_add")}
    )
    git_repo.git("mv", "src/lib.rs", "src/core.rs")
    git_repo.commit("Move the library", {"src/core.rs": LIB_V2 + "\n#[test]\nfn more() {}\n"})
    git_repo.git("rm", "-q", "internal/kind/kind_string.go")
    git_repo.commit("Drop generated code")
    drop, move, tweak, fix, add = walk(git_repo.root)
    assert signals_by_path(add) == {
        "README.md": (),
        "internal/kind/kind_string.go": ("generated-header",),
        "src/lib.rs": ("rust-inline-tests", "rust-tests-added"),
        "web/bundle.js": ("minified",),
        "web/logo.js": (),
    }
    assert signals_by_path(fix) == {"src/lib.rs": ("rust-inline-tests", "rust-tests-added")}
    assert signals_by_path(tweak) == {"src/lib.rs": ("rust-inline-tests",)}
    (renamed,) = move.files
    assert renamed.old_path == "src/lib.rs"
    assert renamed.signals == ("rust-inline-tests", "rust-tests-added")
    # A deleted file is judged as it was in the parent.
    assert signals_by_path(drop) == {"internal/kind/kind_string.go": ("generated-header",)}
    assert all(not f.signals for c in walk(git_repo.root, content=False) for f in c.files)


def test_paths_with_newlines_are_skipped(git_repo: GitRepo) -> None:
    git_repo.commit("odd name", {"a\nb.go": GENERATED_GO, "ok.go": GENERATED_GO})
    (commit,) = walk(git_repo.root)
    assert signals_by_path(commit) == {"a\nb.go": (), "ok.go": ("generated-header",)}


def test_blob_reader_protocol(git_repo: GitRepo) -> None:
    sha = git_repo.commit("one", {"src/a.go": "package a\n", "src/b.go": "0123456789\n"})
    with BlobReader(git_repo.root, limit=4) as blobs:
        assert blobs.read(sha, "src/b.go") == b"0123"
        assert blobs.read(sha, "src") is None  # a tree, read and dropped
        assert blobs.read(sha, "missing.go") is None
        assert blobs.read("0" * 40, "src/a.go") is None
        assert blobs.read(sha, "src/a.go") == b"pack"  # still in sync after all of the above
    with BlobReader(git_repo.root) as blobs:
        assert blobs.read(sha, "src/a.go") == b"package a\n"
        blobs.close()  # closing twice is harmless


def test_blob_reader_reports_a_dead_git(tmp_path: Path) -> None:
    with (
        BlobReader(tmp_path) as blobs,
        pytest.raises(GitError, match="git cat-file stopped: fatal"),
    ):
        blobs.read("HEAD", "a.go")


def test_blob_reader_reports_a_broken_pipe(git_repo: GitRepo) -> None:
    sha = git_repo.commit("one", {"a.go": "package a\n"})
    with BlobReader(git_repo.root) as blobs:
        blobs._proc.kill()
        blobs._proc.wait()
        with pytest.raises(GitError, match="git cat-file stopped"):
            blobs.read(sha, "a.go")


class FakeProc:
    """Stands in for the git process to feed the reader canned output."""

    def __init__(self, output: bytes) -> None:
        self.stdin = io.BytesIO()
        self.stdout = io.BytesIO(output)
        self.stderr = io.BytesIO(b"")
        self.waits = 0

    def poll(self) -> None:
        return None

    def kill(self) -> None:
        pass

    def wait(self, timeout: float | None = None) -> int:
        self.waits += 1
        if timeout is not None:
            raise subprocess.TimeoutExpired("git", timeout)
        return 0


def fake_reader(tmp_path: Path, output: bytes) -> tuple[BlobReader, FakeProc]:
    reader = BlobReader(tmp_path)
    reader.close()
    fake = FakeProc(output)
    reader._proc = fake  # type: ignore[assignment]
    return reader, fake


def test_blob_reader_rejects_unexpected_output(tmp_path: Path) -> None:
    reader, _ = fake_reader(tmp_path, b"what is this\n")
    with pytest.raises(GitError, match="unexpected git cat-file output"):
        reader.read("HEAD", "a.go")


def test_blob_reader_detects_truncated_objects(tmp_path: Path) -> None:
    reader, _ = fake_reader(tmp_path, b"a" * 40 + b" blob 10\n0123")
    with pytest.raises(GitError, match="stopped: no error message"):
        reader.read("HEAD", "a.go")


def test_blob_reader_kills_git_that_does_not_exit(tmp_path: Path) -> None:
    reader, fake = fake_reader(tmp_path, b"")
    reader.close()
    assert fake.waits == 2  # the timed wait, then the wait after kill


def test_blob_reader_reports_missing_git(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PATH", "")
    with pytest.raises(GitError, match="not found"):
        BlobReader(tmp_path)


def test_file_details_for_root_commits_and_deletions(git_repo: GitRepo) -> None:
    sha = git_repo.commit("root", {"src/lib.rs": LIB_V1})
    root = Commit(sha, (), "2024-01-01T00:00:00+00:00", "root", ())
    gone = Commit("0" * 40, (), "2024-01-01T00:00:00+00:00", "gone", ())
    with BlobReader(git_repo.root) as blobs:
        change = file_details(root, FileChange("src/lib.rs", 11, 0), None, blobs)
        assert change.signals == ("rust-inline-tests", "rust-tests-added")
        # Missing at the commit and no parent to fall back to: no signals.
        assert file_details(gone, FileChange("src/lib.rs", 0, 11), None, blobs).signals == ()


def test_a_crate_root_that_mentions_generated_bindings_is_a_candidate(git_repo: GitRepo) -> None:
    # A comment such as "Include the auto-generated bindings" used to mark the whole file
    # generated, which dropped it from source and rejected the fix as no-source.
    head = (
        "//! Safe wrappers over the C library.\n\n// Include the auto-generated bindings\n"
        'mod ffi {\n    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));\n}\n\n'
    )
    git_repo.commit("Add wrappers", {"src/lib.rs": head + LIB_V1, "Cargo.toml": "[package]\n"})
    git_repo.commit("Fix pass error mapping (fixes #42)", {"src/lib.rs": head + LIB_V2})
    fix, _ = walk(git_repo.root)
    assert signals_by_path(fix) == {"src/lib.rs": ("rust-inline-tests", "rust-tests-added")}
    result = mine([fix])
    assert [c.commit.sha for c in result.candidates] == [fix.sha]
